### ISSUE TITLE
Ignoring NPM optionalDependencies

### ISSUE THREAD

**Issue by mwagz** [licensee/licensed#98]
I'm currently using `licensed` in my project. This project also has a dependency of the Webpacker gem, which includes an npm dependency of `@rails/webpacker`. `fsevents` is an optional dependency through the following dependency tree:

```
@rails/webpacker => webpack => watchpack => chokidar => fsevents
```

This means that `licensed status` will detect it. The problem is that `fsevents` is an `optionalDependency` in this particular NPM package. So if it fails to install, the package just falls back to IIRC, but `licensed` still wants it to be present. So I receive the output in [this Gist](https://gist.github.com/mwagz/eb758a261619ce05bb453dcf2e7a0b37).

I think, ideally, npm packages that are "optional" would be ignored by licensed. Adding it to ignored does not seem to work.

**Comment by jonabc** [comment]
@mwagz thanks for the bug report.  If you want to open a PR to fix this issue I'd be happy to review it, otherwise I'll try to get to this soon.

**Comment by mwagz** [comment]
@jonabc Thanks and sure. I'm looking at it now. It seems like we're failing because it can't find it in `node_modules` before we check if it's ignored. I'm going to try to check if it's be designated as ignored before we fail. I'll let you know if I'm unable to figure anything out.
